[workspace]
resolver = "2"
members = [
    "extend/lua",
    "extend/luakit",
    "extend/ljson",
    "extend/ltoml",
    "extend/lyaml",
    "extend/lstdfs",
    "extend/ltimer",
    "core/quanta",
]

[profile.release]
# strip = true
# codegen-units = 1
# lto = true
# panic = "abort"