[package]
name = "luapb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type =["cdylib"]

[dependencies]
libc = "0.2.169"
once_cell = "1.20.2"
lua = { path = "../lua"}
luakit = { path = "../luakit"}
