[package]
name = "lcsv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type =["cdylib"]

[dependencies]
csv = "1.3.1"
libc = "0.2.169"
lua = { path = "../lua"}
luakit = { path = "../luakit"}
